project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: .
preserve_hierarchy: true

files:
  - source: /public/locales/en_US/*.json
    translation: /public/locales/%locale_with_underscore%/%original_file_name%
